In [ ]:
# Instalar e importar bibliotecas
!pip install pygsheets
import pygsheets
import pandas as pd

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pygsheets
  Downloading pygsheets-2.0.6-py3-none-any.whl (158 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.2/158.2 KB 3.8 MB/s eta 0:00:00
Collecting google-auth-oauthlib>=0.7.1
  Downloading google_auth_oauthlib-0.8.0-py2.py3-none-any.whl (19 kB)
Requirement already satisfied: google-api-python-client>=2.50.0 in /usr/local/lib/python3.8/dist-packages (from pygsheets) (2.70.0)
Requirement already satisfied: google-auth-httplib2>=0.1.0 in /usr/local/lib/python3.8/dist-packages (from google-api-python-client>=2.50.0->pygsheets) (0.1.0)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /usr/local/lib/python3.8/dist-packages (from google-api-python-client>=2.50.0->pygsheets) (4.1.1)
Requirement already satisfied: httplib2<1dev,>=0.15.0 in /usr/local/lib/python3.8/dist-packages (from google-api-python-client>=2.50.0->pygsheets) (0.17.4)
Requirement already satisfied: google-auth<3.0.0dev,>=1.19.0 in /usr/local/lib/python3.8/dist-packages (from google-api-python-client>=2.50.0->pygsheets) (2.15.0)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5 in /usr/local/lib/python3.8/dist-packages (from google-api-python-client>=2.50.0->pygsheets) (2.11.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.8/dist-packages (from google-auth-oauthlib>=0.7.1->pygsheets) (1.3.1)
Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.56.2 in /usr/local/lib/python3.8/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client>=2.50.0->pygsheets) (1.57.1)
Requirement already satisfied: requests<3.0.0dev,>=2.18.0 in /usr/local/lib/python3.8/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client>=2.50.0->pygsheets) (2.25.1)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5 in /usr/local/lib/python3.8/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client>=2.50.0->pygsheets) (3.19.6)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from google-auth<3.0.0dev,>=1.19.0->google-api-python-client>=2.50.0->pygsheets) (5.2.0)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.8/dist-packages (from google-auth<3.0.0dev,>=1.19.0->google-api-python-client>=2.50.0->pygsheets) (1.15.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.8/dist-packages (from google-auth<3.0.0dev,>=1.19.0->google-api-python-client>=2.50.0->pygsheets) (4.9)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.8/dist-packages (from google-auth<3.0.0dev,>=1.19.0->google-api-python-client>=2.50.0->pygsheets) (0.2.8)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.8/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.7.1->pygsheets) (3.2.2)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /usr/local/lib/python3.8/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0dev,>=1.19.0->google-api-python-client>=2.50.0->pygsheets) (0.4.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests<3.0.0dev,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client>=2.50.0->pygsheets) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests<3.0.0dev,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client>=2.50.0->pygsheets) (2022.12.7)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests<3.0.0dev,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client>=2.50.0->pygsheets) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests<3.0.0dev,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client>=2.50.0->pygsheets) (2.10)
Installing collected packages: google-auth-oauthlib, pygsheets
  Attempting uninstall: google-auth-oauthlib
    Found existing installation: google-auth-oauthlib 0.4.6
    Uninstalling google-auth-oauthlib-0.4.6:
      Successfully uninstalled google-auth-oauthlib-0.4.6
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorboard 2.9.1 requires google-auth-oauthlib<0.5,>=0.4.1, but you have google-auth-oauthlib 0.8.0 which is incompatible.
Successfully installed google-auth-oauthlib-0.8.0 pygsheets-2.0.6

In [ ]:
# Autentica com API do Google
api = pygsheets.authorize(client_secret = "api.json")
api

In [ ]:
# Importar tabela usando a URL
api.open_by_url(
    "https://docs.google.com/spreadsheets/d/19L1EH_Bv2__ydVJvkmL5QMaXc7PS9Vtplh2uZ9EgViU/edit?usp=sharing"
    ).worksheet_by_title("Oceania").get_as_df()

        country continent  year  lifeExp       pop    gdpPercap
0     Australia   Oceania  1952   69.120   8691212  10039.59564
1     Australia   Oceania  1957   70.330   9712569  10949.64959
2     Australia   Oceania  1962   70.930  10794968  12217.22686
3     Australia   Oceania  1967   71.100  11872264  14526.12465
4     Australia   Oceania  1972   71.930  13177000  16788.62948
5     Australia   Oceania  1977   73.490  14074100  18334.19751
6     Australia   Oceania  1982   74.740  15184200  19477.00928
7     Australia   Oceania  1987   76.320  16257249  21888.88903
8     Australia   Oceania  1992   77.560  17481977  23424.76683
9     Australia   Oceania  1997   78.830  18565243  26997.93657
10    Australia   Oceania  2002   80.370  19546792  30687.75473
11    Australia   Oceania  2007   81.235  20434176  34435.36744
12  New Zealand   Oceania  1952   69.390   1994794  10556.57566
13  New Zealand   Oceania  1957   70.260   2229407  12247.39532
14  New Zealand   Oceania  1962   71.240   2488550  13175.67800
15  New Zealand   Oceania  1967   71.520   2728150  14463.91893
16  New Zealand   Oceania  1972   71.890   2929100  16046.03728
17  New Zealand   Oceania  1977   72.220   3164900  16233.71770
18  New Zealand   Oceania  1982   73.840   3210650  17632.41040
19  New Zealand   Oceania  1987   74.320   3317166  19007.19129
20  New Zealand   Oceania  1992   76.330   3437674  18363.32494
21  New Zealand   Oceania  1997   77.550   3676187  21050.41377
22  New Zealand   Oceania  2002   79.110   3908037  23189.80135
23  New Zealand   Oceania  2007   80.204   4115771  25185.00911

In [ ]:
# Criar arquivo no Drive
minha_planilha = api.create("orcamento_mensal2")

# Criar folha dentro da planilha
minha_planilha.add_worksheet("folha1")

# Inserir dados na "folha1"
(
   minha_planilha
  .worksheet_by_title("folha1")
  .set_dataframe(
      df = pd.DataFrame({"x": [1, 2, 3], "y": ["a", "b", "c"]}),
      start = (1, 1)
      )
)

# Deletar folha "Sheet1"
minha_planilha.del_worksheet(minha_planilha.worksheet())  # função de dentro retorna a primeira folha e função de fora deleta a mesma

# Importar dados criados no Sheets
api.open_by_url(
    "https://docs.google.com/spreadsheets/d/1oa4ppbQC2nDpXoyts5J0z3Nvj8kRth-AaQJIrlyxG6E/edit?usp=sharing"
    ).worksheet_by_title("folha1").get_as_df()

   x  y
0  1  a
1  2  b
2  3  c