In [3]:
#  Bibliotecas
from bcb import sgs # Instalar pip install python-bcb
import pandas as pd
import ipeadatapy as ipea # Instalar pip install ipeadatapy

In [2]:
# Importar 1 série do SGS/BCB
dados_sgs =  sgs.get(codes = 22099, start = "2010-01-01") # olhar no site "https://www3.bcb.gov.br/sgspub/"
dados_sgs

             22099
Date
2010-01-01  152.53
2010-04-01  158.86
2010-07-01  163.63
2010-10-01  163.55
2011-01-01  160.45
2011-04-01  166.33
2011-07-01  169.41
2011-10-01  167.75
2012-01-01  163.19
2012-04-01  167.97
2012-07-01  173.63
2012-10-01  171.91
2013-01-01  167.63
2013-04-01  174.73
2013-07-01  178.42
2013-10-01  176.26
2014-01-01  173.45
2014-04-01  173.97
2014-07-01  177.28
2014-10-01  175.86
2015-01-01  170.64
2015-04-01  169.20
2015-07-01  169.72
2015-10-01  166.15
2016-01-01  161.87
2016-04-01  163.75
2016-07-01  165.55
2016-10-01  162.39
2017-01-01  162.33
2017-04-01  165.04
2017-07-01  168.27
2017-10-01  166.58
2018-01-01  165.42
2018-04-01  167.71
2018-07-01  171.73
2018-10-01  169.17
2019-01-01  166.91
2019-04-01  169.68
2019-07-01  173.64
2019-10-01  172.03
2020-01-01  167.60
2020-04-01  152.48
2020-07-01  168.37
2020-10-01  171.46
2021-01-01  170.53
2021-04-01  171.38
2021-07-01  175.46
2021-10-01  173.96
2022-01-01  173.05
2022-04-01  177.45
2022-07-01  183.04
2022-10-01  178.65
2023-01-01  180.74
2023-04-01  184.28
2023-07-01  187.35
2023-10-01  182.90
2024-01-01  185.36
2024-04-01  190.43
2024-07-01  194.94

In [5]:
# Importar múltiplas séries do SGS/BCB
dados_sgs_m =  sgs.get(codes = {"pib": 22099, "ipca": 433}) # olhar no site "https://www3.bcb.gov.br/sgspub/"
dados_sgs_m.tail(10)

               pib  ipca
Date
2024-04-01  190.43  0.38
2024-05-01     NaN  0.46
2024-06-01     NaN  0.21
2024-07-01  194.94  0.38
2024-08-01     NaN -0.02
2024-09-01     NaN  0.44
2024-10-01     NaN  0.56
2024-11-01     NaN  0.39
2024-12-01     NaN  0.52
2025-01-01     NaN  0.16

In [ ]:
# Coleta de dados do IPCA (Expectativa anual) com o pandas
dados_expectativas = pd.read_csv(
    filepath_or_buffer = "https://olinda.bcb.gov.br/olinda/servico/Expectativas/versao/v1/odata/Expectativas" + 
    "MercadoAnuais?$filter=Indicador%20eq%20'IPCA'%20and%20Data" +
    "%20ge%20'2021-01-01'&$format=text/csv",    # O link é retirado do seguinte local "https://olinda.bcb.gov.br/olinda/servico/Expectativas/versao/v1/aplicacao#!/recursos"
    decimal = ","
)
dados_expectativas

      Indicador  IndicadorDetalhe  ... numeroRespondentes  baseCalculo
0          IPCA               NaN  ...                100            0
1          IPCA               NaN  ...                 70            0
2          IPCA               NaN  ...                100            0
3          IPCA               NaN  ...                 91            0
4          IPCA               NaN  ...                 82            0
...         ...               ...  ...                ...          ...
10405      IPCA               NaN  ...                105            1
10406      IPCA               NaN  ...                102            1
10407      IPCA               NaN  ...                 88            1
10408      IPCA               NaN  ...                 81            1
10409      IPCA               NaN  ...                 71            1

[10410 rows x 11 columns]

In [ ]:
# Obter código das séries do IPEADATA
codigos_ipeadata = ipea.list_series()
codigos_ipeadata

                     CODE                                               NAME
0            ABATE_ABPEAV                   Abate - aves - peso das carcaças
1            ABATE_ABQUBV                       Abate - bovinos - quantidade
2        ABATE12_ABPEVA12                  Abate - vacas - peso das carcaças
3        ABATE12_ABQUBO12                          Abate - bois - quantidade
4        ABATE12_ABQUBV12                       Abate - bovinos - quantidade
...                   ...                                                ...
3035  PNADCT_TXPARTCUF_SI  Taxa de participação - sem instrução ou equiva...
3036           PNAD_IAGRV         Domicílios com insegurança alimentar grave
3037           PNAD_IALEV          Domicílios com insegurança alimentar leve
3038           PNAD_IAMOD      Domicílios com insegurança alimentar moderada
3039           PNAD_SATOT                 Domicílios com segurança alimentar

[3040 rows x 2 columns]

In [7]:
# Buscar série de interesse
codigos_ipeadata[codigos_ipeadata.CODE.str.contains("CAGED")]

                      CODE                                              NAME
1181         CAGED12_ADMIS                  Empregados - admissões - INATIVA
1182      CAGED12_ADMISN12  Empregados - admissões - sem ajuste - novo Caged
1183   CAGED12_ADMISNAJU12  Empregados - admissões - com ajuste - novo Caged
1184        CAGED12_DESLIG                  Empregados - demissões - INATIVA
1185     CAGED12_DESLIGN12  Empregados - demissões - sem ajuste - novo Caged
1186  CAGED12_DESLIGNAJU12  Empregados - demissões - com ajuste - novo Caged
1187       CAGED12_SALDO12                      Empregados - saldo - INATIVA
1188      CAGED12_SALDON12      Empregados - saldo - sem ajuste - novo Caged
1189   CAGED12_SALDONAJU12      Empregados - saldo - com ajuste - novo Caged

In [10]:
# Coleta de dados do CAGED pelo IPEADATA
dados_ipeadata = ipea.timeseries(series = "CAGED12_SALDON12")
dados_ipeadata

,CODE,RAW DATE,DAY,MONTH,YEAR,VALUE (Pessoa)
DATE,,,,,,
2020-01-01,CAGED12_SALDON12,2020-01-01T00:00:00-03:00,1,1,2020,92678.0
2020-02-01,CAGED12_SALDON12,2020-02-01T00:00:00-03:00,1,2,2020,198368.0
2020-03-01,CAGED12_SALDON12,2020-03-01T00:00:00-03:00,1,3,2020,-232316.0
2020-04-01,CAGED12_SALDON12,2020-04-01T00:00:00-03:00,1,4,2020,-902317.0
2020-05-01,CAGED12_SALDON12,2020-05-01T00:00:00-03:00,1,5,2020,-352790.0
2020-06-01,CAGED12_SALDON12,2020-06-01T00:00:00-03:00,1,6,2020,-23111.0
2020-07-01,CAGED12_SALDON12,2020-07-01T00:00:00-03:00,1,7,2020,123297.0
2020-08-01,CAGED12_SALDON12,2020-08-01T00:00:00-03:00,1,8,2020,238125.0
2020-09-01,CAGED12_SALDON12,2020-09-01T00:00:00-03:00,1,9,2020,313564.0
2020-10-01,CAGED12_SALDON12,2020-10-01T00:00:00-03:00,1,10,2020,388938.0
2020-11-01,CAGED12_SALDON12,2020-11-01T00:00:00-03:00,1,11,2020,408948.0
2020-12-01,CAGED12_SALDON12,2020-12-01T00:00:00-03:00,1,12,2020,-82118.0
2021-01-01,CAGED12_SALDON12,2021-01-01T00:00:00-03:00,1,1,2021,257059.0
2021-02-01,CAGED12_SALDON12,2021-02-01T00:00:00-03:00,1,2,2021,397915.0
2021-03-01,CAGED12_SALDON12,2021-03-01T00:00:00-03:00,1,3,2021,176330.0
2021-04-01,CAGED12_SALDON12,2021-04-01T00:00:00-03:00,1,4,2021,113922.0
2021-05-01,CAGED12_SALDON12,2021-05-01T00:00:00-03:00,1,5,2021,278705.0
2021-06-01,CAGED12_SALDON12,2021-06-01T00:00:00-03:00,1,6,2021,310036.0
2021-07-01,CAGED12_SALDON12,2021-07-01T00:00:00-03:00,1,7,2021,316725.0
2021-08-01,CAGED12_SALDON12,2021-08-01T00:00:00-03:00,1,8,2021,373344.0
2021-09-01,CAGED12_SALDON12,2021-09-01T00:00:00-03:00,1,9,2021,316993.0
2021-10-01,CAGED12_SALDON12,2021-10-01T00:00:00-03:00,1,10,2021,253083.0
2021-11-01,CAGED12_SALDON12,2021-11-01T00:00:00-03:00,1,11,2021,324112.0
2021-12-01,CAGED12_SALDON12,2021-12-01T00:00:00-03:00,1,12,2021,-265811.0
2022-01-01,CAGED12_SALDON12,2022-01-01T00:00:00-03:00,1,1,2022,155178.0
2022-02-01,CAGED12_SALDON12,2022-02-01T00:00:00-03:00,1,2,2022,328507.0
2022-03-01,CAGED12_SALDON12,2022-03-01T00:00:00-03:00,1,3,2022,136189.0
2022-04-01,CAGED12_SALDON12,2022-04-01T00:00:00-03:00,1,4,2022,196966.0
2022-05-01,CAGED12_SALDON12,2022-05-01T00:00:00-03:00,1,5,2022,277018.0
2022-06-01,CAGED12_SALDON12,2022-06-01T00:00:00-03:00,1,6,2022,277944.0
2022-07-01,CAGED12_SALDON12,2022-07-01T00:00:00-03:00,1,7,2022,218902.0
2022-08-01,CAGED12_SALDON12,2022-08-01T00:00:00-03:00,1,8,2022,278639.0
2022-09-01,CAGED12_SALDON12,2022-09-01T00:00:00-03:00,1,9,2022,278085.0
2022-10-01,CAGED12_SALDON12,2022-10-01T00:00:00-03:00,1,10,2022,159454.0
2022-11-01,CAGED12_SALDON12,2022-11-01T00:00:00-03:00,1,11,2022,135495.0
2022-12-01,CAGED12_SALDON12,2022-12-01T00:00:00-03:00,1,12,2022,-431011.0
2023-01-01,CAGED12_SALDON12,2023-01-01T00:00:00-03:00,1,1,2023,83297.0
2023-02-01,CAGED12_SALDON12,2023-02-01T00:00:00-03:00,1,2,2023,241785.0
2023-03-01,CAGED12_SALDON12,2023-03-01T00:00:00-03:00,1,3,2023,195171.0
2023-04-01,CAGED12_SALDON12,2023-04-01T00:00:00-03:00,1,4,2023,180005.0
2023-05-01,CAGED12_SALDON12,2023-05-01T00:00:00-03:00,1,5,2023,155270.0
2023-06-01,CAGED12_SALDON12,2023-06-01T00:00:00-03:00,1,6,2023,157198.0
2023-07-01,CAGED12_SALDON12,2023-07-01T00:00:00-03:00,1,7,2023,142702.0
2023-08-01,CAGED12_SALDON12,2023-08-01T00:00:00-03:00,1,8,2023,220844.0
2023-09-01,CAGED12_SALDON12,2023-09-01T00:00:00-03:00,1,9,2023,211764.0
2023-10-01,CAGED12_SALDON12,2023-10-01T00:00:00-03:00,1,10,2023,190366.0
2023-11-01,CAGED12_SALDON12,2023-11-01T00:00:00-03:00,1,11,2023,130097.0
2023-12-01,CAGED12_SALDON12,2023-12-01T00:00:00-03:00,1,12,2023,-430159.0
2024-01-01,CAGED12_SALDON12,2024-01-01T00:00:00-03:00,1,1,2024,180395.0
2024-02-01,CAGED12_SALDON12,2024-02-01T00:00:00-03:00,1,2,2024,306111.0
2024-03-01,CAGED12_SALDON12,2024-03-01T00:00:00-03:00,1,3,2024,244315.0
2024-04-01,CAGED12_SALDON12,2024-04-01T00:00:00-03:00,1,4,2024,240033.0
2024-05-01,CAGED12_SALDON12,2024-05-01T00:00:00-03:00,1,5,2024,131811.0
2024-06-01,CAGED12_SALDON12,2024-06-01T00:00:00-03:00,1,6,2024,201705.0
2024-07-01,CAGED12_SALDON12,2024-07-01T00:00:00-03:00,1,7,2024,188021.0
2024-08-01,CAGED12_SALDON12,2024-08-01T00:00:00-03:00,1,8,2024,232513.0
2024-09-01,CAGED12_SALDON12,2024-09-01T00:00:00-03:00,1,9,2024,247818.0
2024-10-01,CAGED12_SALDON12,2024-10-01T00:00:00-03:00,1,10,2024,132714.0
2024-11-01,CAGED12_SALDON12,2024-11-01T00:00:00-03:00,1,11,2024,106625.0
2024-12-01,CAGED12_SALDON12,2024-12-01T00:00:00-03:00,1,12,2024,-535547.0

In [12]:
# Coleta de dados do Sidra
# Importando tabela 7060 do Sidra
dados_sidra = pd.read_json(
    path_or_buf = "https://apisidra.ibge.gov.br/values/t/7060" +
    "/n1/all/v/63/p/all/c315/7169/d/v63%202?formato=json" # Para deixar no formato de Json utilizar o comando ao final "?formato=json"
)
dados_sidra

,NC,NN,MC,MN,V,D1C,D1N,D2C,D2N,D3C,D3N,D4C,D4N
0,Nível Territorial (Código),Nível Territorial,Unidade de Medida (Código),Unidade de Medida,Valor,Brasil (Código),Brasil,Variável (Código),Variável,Mês (Código),Mês,"Geral, grupo, subgrupo, item e subitem (Código)","Geral, grupo, subgrupo, item e subitem"
1,1,Brasil,2,%,0.21,1,Brasil,63,IPCA - Variação mensal,202001,janeiro 2020,7169,Índice geral
2,1,Brasil,2,%,0.25,1,Brasil,63,IPCA - Variação mensal,202002,fevereiro 2020,7169,Índice geral
3,1,Brasil,2,%,0.07,1,Brasil,63,IPCA - Variação mensal,202003,março 2020,7169,Índice geral
4,1,Brasil,2,%,-0.31,1,Brasil,63,IPCA - Variação mensal,202004,abril 2020,7169,Índice geral
...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,1,Brasil,2,%,0.44,1,Brasil,63,IPCA - Variação mensal,202409,setembro 2024,7169,Índice geral
58,1,Brasil,2,%,0.56,1,Brasil,63,IPCA - Variação mensal,202410,outubro 2024,7169,Índice geral
59,1,Brasil,2,%,0.39,1,Brasil,63,IPCA - Variação mensal,202411,novembro 2024,7169,Índice geral
60,1,Brasil,2,%,0.52,1,Brasil,63,IPCA - Variação mensal,202412,dezembro 2024,7169,Índice geral
61,1,Brasil,2,%,0.16,1,Brasil,63,IPCA - Variação mensal,202501,janeiro 2025,7169,Índice geral